### PR TITLE
Update compiler version

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@fbriol, please don't merge this PR until all tests pass

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
@fbriol, this PR didn't pass the tests yet. Why did you merge it?

**Comment by fbriol** [comment]
I made a mistake. I'm sorry. I'm sorry. I'm not really used to doing that. Sorry again.

**Comment by isuruf** [comment]
Okay. Let's see what happens with the build now

**Comment by fbriol** [comment]
The construction is OK ;)

**Pull request merged**
